import type { ReactNode } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { I18nextProvider } from 'react-i18next';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import { enCatalog } from './../apps/web/.ds-i18n';

// A dedicated instance, NOT the app's src/i18n — that module builds its catalog
// with Vite's `import.meta.glob`, which esbuild cannot evaluate. Same English
// copy, statically imported (see .ds-i18n.ts, generated by gen-entry.mjs).
const i18n = i18next.createInstance();
void i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  resources: { en: { translation: enCatalog } },
  interpolation: { escapeValue: false },
});

/**
 * Preview harness for design-sync cards — context + surface.
 *
 * Two problems this solves, both preview-only:
 *
 * 1. **Context.** Campfire's components are app components: they read
 *    react-router (`Link`), i18next (`useTranslation`), and react-query
 *    (`useQuery`). Rendered bare, anything touching a router throws and falls
 *    back to the floor card. The real `i18n` instance is used rather than a stub
 *    so previews show the app's actual copy, not raw translation keys.
 *
 * 2. **Surface.** Campfire is dark-only: `styles.css` puts the app background on
 *    `body`, but the generated card chrome sets `body{background:#fff}` inline
 *    AFTER the stylesheet link. This re-establishes the real surface inside
 *    `#root` using only the design system's own tokens — it invents no colour,
 *    spacing, or type of its own.
 *
 * Wired via `cfg.provider`, and deliberately excluded from the component list:
 * it ships in the bundle as a harness, never as a card to compose with.
 */
const queryClient = new QueryClient({
  // Previews are static: never retry, never refetch, so a failed query settles
  // immediately into its rendered error/empty state instead of spinning.
  defaultOptions: {
    queries: { retry: false, refetchOnWindowFocus: false, staleTime: Infinity, gcTime: Infinity },
    mutations: { retry: false },
  },
});

export function DsPreviewSurface({ children }: { children?: ReactNode }) {
  return (
    <QueryClientProvider client={queryClient}>
      <I18nextProvider i18n={i18n}>
        <MemoryRouter>
          <div
            style={{
              background: 'var(--color-bg)',
              color: 'var(--color-text)',
              fontFamily: 'var(--font-body)',
              fontSize: 'var(--type-body)',
              // Deliberately NO padding/minHeight: the card's floor-card
              // fallback fires on a zero-height root, so an unauthored
              // component must still collapse to nothing rather than render as
              // an empty dark box. Authored previews supply their own spacing.
            }}
          >
            {children}
          </div>
        </MemoryRouter>
      </I18nextProvider>
    </QueryClientProvider>
  );
}
