#!/usr/bin/env python3
"""
Generate `src/lib/icons/uiExtras.generated.ts` — a small, always-bundled set of
game-icons bodies for the high-frequency *app chrome* slugs that this app renders
in nav, chips, pills, empty states and guard screens but that aren't in the
curated ~180 catalog (`catalog.generated.ts`, #302).

Those slugs otherwise resolve only via the lazy full-index + shard fetch
(`resolveIcon`), so their very first paint is blank until a shard lands. Chrome
icons are shown constantly and should render synchronously, so we inline just
these ~35 bodies (a few KB) and fold them into the synchronous lookup in
`lib/icons/index.ts`. Content icons (compendium/inventory, thousands of slugs)
stay lazy — this is only for fixed, ever-present UI chrome.

Bodies come from the already-generated shards (`public/icons/shards/*.json`) and
metadata from `fullIndex.generated.ts`; run after `generate_full_catalog.py`.
When you introduce a new always-visible chrome icon, add its slug to UI_SLUGS
below and re-run:  python3 scripts/icons/generate_ui_extras.py
"""
from __future__ import annotations
import json
import re
from pathlib import Path

WEB_ROOT = Path(__file__).resolve().parents[2]  # apps/web
ICONS_DIR = WEB_ROOT / "src" / "lib" / "icons"
SHARDS_DIR = WEB_ROOT / "public" / "icons" / "shards"
OUT = ICONS_DIR / "uiExtras.generated.ts"

# High-frequency chrome slugs used across nav/chips/empty-states/guards that are
# NOT in the curated catalog. Keep alphabetised. Add new chrome slugs here.
UI_SLUGS = [
    "archive-register", "black-flag", "calendar", "cancel", "chat-bubble",
    "cog", "conversation", "crystal-ball", "database", "envelope", "eyeball",
    "film-strip", "hand", "hazard-sign", "life-buoy", "light-bulb",
    "linked-rings", "magnifying-glass", "microphone", "oak-leaf", "padlock",
    "person", "position-marker", "ringing-bell", "robot-golem", "scales",
    "secret-book", "shaking-hands", "sight-disabled", "sparkles", "stopwatch",
    "top-hat", "trash-can", "tv", "vote",
]


def full_index_meta() -> dict[str, dict]:
    text = (ICONS_DIR / "fullIndex.generated.ts").read_text()
    meta: dict[str, dict] = {}
    for m in re.finditer(
        r'\{\s*slug:\s*"([^"]+)",\s*name:\s*"([^"]*)",\s*artist:\s*"([^"]*)",'
        r'\s*category:\s*"([^"]*)",\s*shard:\s*(\d+)',
        text,
    ):
        slug, name, artist, category, shard = m.groups()
        meta[slug] = {"name": name, "category": category, "artist": artist, "shard": int(shard)}
    return meta


def main() -> None:
    meta = full_index_meta()
    shard_cache: dict[int, dict] = {}
    entries = []
    for slug in sorted(set(UI_SLUGS)):
        info = meta.get(slug)
        if not info:
            raise SystemExit(f"slug not in full index: {slug}")
        shard = info["shard"]
        if shard not in shard_cache:
            shard_cache[shard] = json.loads((SHARDS_DIR / f"shard-{shard:03d}.json").read_text())
        body = shard_cache[shard].get(slug)
        if not body:
            raise SystemExit(f"body missing for slug: {slug} (shard {shard})")
        entries.append({"slug": slug, "name": info["name"], "category": info["category"],
                        "artist": info["artist"], "body": body})

    lines = [
        "// AUTO-GENERATED by scripts/icons/generate_ui_extras.py — do not edit by hand.",
        "// High-frequency app-chrome icons inlined for synchronous first paint (see the",
        "// generator's docstring). Regenerate after changing UI_SLUGS there.",
        'import type { GameIconEntry } from "./catalog.generated";',
        "",
        "export const UI_EXTRA_ICONS: GameIconEntry[] = [",
    ]
    for e in entries:
        body = json.dumps(e["body"])
        lines.append(
            f'  {{ slug: {json.dumps(e["slug"])}, name: {json.dumps(e["name"])}, '
            f'category: {json.dumps(e["category"])}, artist: {json.dumps(e["artist"])}, '
            f'tags: [], body: {body} }},'
        )
    lines.append("];")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(entries)} icons)")


if __name__ == "__main__":
    main()
